name: test-actions
run-name: ${{ github.actor }} is learning GitHub Actions
env: 
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
on: 
  push:
  workflow_dispatch:
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - run: npm install -g bats
  #     - run: bats -v

  test01:
    runs-on: ubuntu-latest
    env:  
      TEST_ENV: test_env01
      T_S: ${{ secrets.TEST_SECRET }}
      T_V: ${{ vars.TEST_VARIABLE }}
    steps:
      - run: echo $SHELL
      - uses: actions/checkout@v4
      - run: pwd
      - name: Testing Env 
        run: echo "${{ vars.TEST_VARIABLE }}"  
        # run: echo "${{ vars.TEST_VARIABLE }}"

      - run: echo "${{ vars.TEST_VARIABLE }}"  
      - run: echo "${{ env.TEST_ENV }}"  
      # - run: echo $GITHUB_ENV
      - run: echo "variable from shell environment :$env_var"
      # - run: |
      #   pwd
      #   ls
